//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.CidadeServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cidade", Namespace="http://schemas.datacontract.org/2004/07/WsTeste.Domain")]
    [System.SerializableAttribute()]
    public partial class Cidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CidadeServico.ICidadeServico")]
    public interface ICidadeServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeServico/BuscaTodasCidades", ReplyAction="http://tempuri.org/ICidadeServico/BuscaTodasCidadesResponse")]
        System.Collections.Generic.List<Presentation.CidadeServico.Cidade> BuscaTodasCidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeServico/BuscaTodasCidades", ReplyAction="http://tempuri.org/ICidadeServico/BuscaTodasCidadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Presentation.CidadeServico.Cidade>> BuscaTodasCidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeServico/BuscaPontos", ReplyAction="http://tempuri.org/ICidadeServico/BuscaPontosResponse")]
        int BuscaPontos(Presentation.CidadeServico.Cidade cidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeServico/BuscaPontos", ReplyAction="http://tempuri.org/ICidadeServico/BuscaPontosResponse")]
        System.Threading.Tasks.Task<int> BuscaPontosAsync(Presentation.CidadeServico.Cidade cidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICidadeServicoChannel : Presentation.CidadeServico.ICidadeServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CidadeServicoClient : System.ServiceModel.ClientBase<Presentation.CidadeServico.ICidadeServico>, Presentation.CidadeServico.ICidadeServico {
        
        public CidadeServicoClient() {
        }
        
        public CidadeServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CidadeServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Presentation.CidadeServico.Cidade> BuscaTodasCidades() {
            return base.Channel.BuscaTodasCidades();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Presentation.CidadeServico.Cidade>> BuscaTodasCidadesAsync() {
            return base.Channel.BuscaTodasCidadesAsync();
        }
        
        public int BuscaPontos(Presentation.CidadeServico.Cidade cidade) {
            return base.Channel.BuscaPontos(cidade);
        }
        
        public System.Threading.Tasks.Task<int> BuscaPontosAsync(Presentation.CidadeServico.Cidade cidade) {
            return base.Channel.BuscaPontosAsync(cidade);
        }
    }
}
